export const weatherIconMap: { [key: string]: string } = {
  '01d': '/src/assets/weather-icons/sunny.svg', // Clear sky (day)
  '01n': '/src/assets/weather-icons/night.svg', // Clear sky (night)
  '02d': '/src/assets/weather-icons/few-cloud-day.svg', // Few clouds (day)
  '02n': '/src/assets/weather-icons/few-cloud-night.svg', // Few clouds (night)
  '03d': '/src/assets/weather-icons/cloud.svg', // Scattered clouds (day)
  '03n': '/src/assets/weather-icons/cloud.svg', // Scattered clouds (night)
  '04d': '/src/assets/weather-icons/clouds-day.svg', // Broken clouds (day)
  '04n': '/src/assets/weather-icons/clouds-night.svg', // Broken clouds (night)
  '09d': '/src/assets/weather-icons/rain-day.svg', // Shower rain (day)
  '09n': '/src/assets/weather-icons/rain-night.svg', // Shower rain (night)
  '10d': '/src/assets/weather-icons/rain-heavy.svg', // Rain (day)
  '10n': '/src/assets/weather-icons/rain-heavy.svg', // Rain (night)
  '11d': '/src/assets/weather-icons/thunderstorm-scattered-day.svg', // Thunderstorm (day)
  '11n': '/src/assets/weather-icons/thunderstorm-scattered-night.svg', // Thunderstorm (night)
  '13d': '/src/assets/weather-icons/snow.svg', // Snow (day)
  '13n': '/src/assets/weather-icons/snow.svg', // Snow (night)
  '50d': '/src/assets/weather-icons/mist-day.svg', // Mist (day)
  '50n': '/src/assets/weather-icons/mist-night.svg'  // Mist (night)
};

export const iconColorMap: { [key: string]: string } = {
  '01d': 'text-yellow-500', // Clear sky (day)
  '01n': 'text-blue-900',   // Clear sky (night)
  '02d': 'text-gray-400',   // Few clouds (day)
  '02n': 'text-gray-600',   // Few clouds (night)
  '03d': 'text-gray-500',   // Scattered clouds (day)
  '03n': 'text-gray-700',   // Scattered clouds (night)
  '04d': 'text-gray-600',   // Broken clouds (day)
  '04n': 'text-gray-800',   // Broken clouds (night)
  '09d': 'text-blue-500',   // Shower rain (day)
  '09n': 'text-blue-700',   // Shower rain (night)
  '10d': 'text-blue-600',   // Rain (day)
  '10n': 'text-blue-800',   // Rain (night)
  '11d': 'text-purple-500', // Thunderstorm (day)
  '11n': 'text-purple-700', // Thunderstorm (night)
  '13d': 'text-gray-200',   // Snow (day)
  '13n': 'text-gray-300',   // Snow (night)
  '50d': 'text-gray-400',   // Mist (day)
  '50n': 'text-gray-500'    // Mist (night)
};